---
title: "IBM Simulations with 10 Epistatic QTL"
author: "Husain Agha"
date: "March 9, 2018"
output: html_document
---

```{r, include=FALSE}

setwd("/Users/hiagh/OneDrive/Documents/GitHub/sim_analyses/results/")

herit <- read.csv("results.epistatic.0.1_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H01 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.2_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H02 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.3_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H03 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.4_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H04 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.5_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H05 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.6_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H06 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.7_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H07 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.8_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H08 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.9_1qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H09 <- length(results[which(is.na(results) == F)])

make.plot.1 <- data.frame(c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))
make.plot.1$QTL <- (nrow(rownames))
make.plot.1$Detection_Rate <- c(H01/(nrow(rownames)*100),H02/(nrow(rownames)*100),H03/(nrow(rownames)*100),H04/(nrow(rownames)*100),H05/(nrow(rownames)*100),H06/(nrow(rownames)*100),H07/(nrow(rownames)*100),H08/(nrow(rownames)*100),H09/(nrow(rownames)*100)
)
names(make.plot.1) <- c("heritability","QTL","Detection_Rate")
```

```{r, include=FALSE}

setwd("/Users/hiagh/OneDrive/Documents/GitHub/sim_analyses/results/")

herit <- read.csv("results.epistatic.0.1_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H01 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.2_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H02 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.3_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H03 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.4_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H04 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.5_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H05 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.6_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H06 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.7_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H07 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.8_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H08 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.9_2qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H09 <- length(results[which(is.na(results) == F)])

make.plot.2 <- data.frame(c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))
make.plot.2$QTL <- (nrow(rownames))
make.plot.2$Detection_Rate <- c(H01/(nrow(rownames)*100),H02/(nrow(rownames)*100),H03/(nrow(rownames)*100),H04/(nrow(rownames)*100),H05/(nrow(rownames)*100),H06/(nrow(rownames)*100),H07/(nrow(rownames)*100),H08/(nrow(rownames)*100),H09/(nrow(rownames)*100)
)
names(make.plot.2) <- c("heritability","QTL","Detection_Rate")
```

###```{r, include=FALSE}

setwd("/Users/hiagh/OneDrive/Documents/GitHub/sim_analyses/results/")

herit <- read.csv("results.epistatic.0.1_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H01 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.2_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H02 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.3_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H03 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.4_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H04 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.5_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H05 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.6_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H06 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.7_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H07 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.8_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H08 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.9_5qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H09 <- length(results[which(is.na(results) == F)])

make.plot.5 <- data.frame(c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))
make.plot.5$QTL <- (nrow(rownames))
make.plot.5$Detection_Rate <- c(H01/(nrow(rownames)*100),H02/(nrow(rownames)*100),H03/(nrow(rownames)*100),H04/(nrow(rownames)*100),H05/(nrow(rownames)*100),H06/(nrow(rownames)*100),H07/(nrow(rownames)*100),H08/(nrow(rownames)*100),H09/(nrow(rownames)*100)
)
names(make.plot.5) <- c("heritability","QTL","Detection_Rate")
###```

```{r, include=FALSE}

setwd("/Users/hiagh/OneDrive/Documents/GitHub/sim_analyses/results/")

herit <- read.csv("results.epistatic.0.1_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H01 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.2_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H02 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.3_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H03 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.4_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H04 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.5_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H05 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.6_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H06 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.7_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H07 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.8_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H08 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.9_10qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H09 <- length(results[which(is.na(results) == F)])

make.plot.10 <- data.frame(c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))
make.plot.10$QTL <- (nrow(rownames))
make.plot.10$Detection_Rate <- c(H01/(nrow(rownames)*100),H02/(nrow(rownames)*100),H03/(nrow(rownames)*100),H04/(nrow(rownames)*100),H05/(nrow(rownames)*100),H06/(nrow(rownames)*100),H07/(nrow(rownames)*100),H08/(nrow(rownames)*100),H09/(nrow(rownames)*100)
)
names(make.plot.10) <- c("heritability","QTL","Detection_Rate")
```

```{r, include=FALSE}

setwd("/Users/hiagh/OneDrive/Documents/GitHub/sim_analyses/results/")

herit <- read.csv("results.epistatic.0.1_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H01 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.2_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H02 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.3_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H03 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.4_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H04 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.5_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H05 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.6_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H06 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.7_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H07 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.8_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H08 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.9_25qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H09 <- length(results[which(is.na(results) == F)])

make.plot.25 <- data.frame(c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))
make.plot.25$QTL <- (nrow(rownames))
make.plot.25$Detection_Rate <- c(H01/(nrow(rownames)*100),H02/(nrow(rownames)*100),H03/(nrow(rownames)*100),H04/(nrow(rownames)*100),H05/(nrow(rownames)*100),H06/(nrow(rownames)*100),H07/(nrow(rownames)*100),H08/(nrow(rownames)*100),H09/(nrow(rownames)*100)
)
names(make.plot.25) <- c("heritability","QTL","Detection_Rate")
```

```{r, include=FALSE}

setwd("/Users/hiagh/OneDrive/Documents/GitHub/sim_analyses/results/")

herit <- read.csv("results.epistatic.0.1_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H01 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.2_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H02 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.3_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H03 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.4_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H04 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.5_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H05 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.6_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H06 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.7_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H07 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.8_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H08 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.9_50qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H09 <- length(results[which(is.na(results) == F)])

make.plot.50 <- data.frame(c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))
make.plot.50$QTL <- (nrow(rownames))
make.plot.50$Detection_Rate <- c(H01/(nrow(rownames)*100),H02/(nrow(rownames)*100),H03/(nrow(rownames)*100),H04/(nrow(rownames)*100),H05/(nrow(rownames)*100),H06/(nrow(rownames)*100),H07/(nrow(rownames)*100),H08/(nrow(rownames)*100),H09/(nrow(rownames)*100)
)
names(make.plot.50) <- c("heritability","QTL","Detection_Rate")
```

```{r, include=FALSE}

setwd("/Users/hiagh/OneDrive/Documents/GitHub/sim_analyses/results/")

herit <- read.csv("results.epistatic.0.1_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H01 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.2_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H02 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.3_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H03 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.4_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H04 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.5_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H05 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.6_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames
H06 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.7_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H07 <- length(results[which(is.na(results) == F)])


herit <- read.csv("results.epistatic.0.8_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H08 <- length(results[which(is.na(results) == F)])

herit <- read.csv("results.epistatic.0.9_100qtl.csv", header = T, row.names = 1)
foo <- (herit[1,])

for(i in 2:nrow(herit)-1){
  if(!i %% 2){
  foo <- rbind(foo, herit[i,])
  
    }
}
rownames <- matrix(NA, nrow = (nrow(herit)-1)/2, ncol = 1)
for(i in 2:nrow(herit)){
  if(!i %% 2){
  rownames[i/2,] <- paste(rownames(herit[i,]), rownames(herit[i+1,]), sep = "x")
}}
rownames(foo) <- c("threshold", rownames)
results <- matrix(NA, nrow = nrow(foo)-1, ncol = 100)
for(i in 1:100){
  for(j in 2:nrow(foo)){
    if(foo[j,i]>foo[1,i]){results[j-1,i] <- print(foo[j,i])}
  }}
row.names(results) <- rownames

H09 <- length(results[which(is.na(results) == F)])

make.plot.100 <- data.frame(c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))
make.plot.100$QTL <- (nrow(rownames))
make.plot.100$Detection_Rate <- c(H01/(nrow(rownames)*100),H02/(nrow(rownames)*100),H03/(nrow(rownames)*100),H04/(nrow(rownames)*100),H05/(nrow(rownames)*100),H06/(nrow(rownames)*100),H07/(nrow(rownames)*100),H08/(nrow(rownames)*100),H09/(nrow(rownames)*100)
)
names(make.plot.100) <- c("heritability","QTL","Detection_Rate")
```


```{r make plot}

make.plot <- rbind(make.plot.1,make.plot.2,make.plot.10,make.plot.25,make.plot.50,make.plot.100)
make.plot <- make.plot[order(make.plot$heritability),]

plot(make.plot$heritability, make.plot$Detection_Rate, type = "o")
lines(make.plot$QTL)
make.plot$QTL <- factor(make.plot$QTL, levels = c(1,2,10,25,50,100))
make.plot$heritability <- factor(make.plot$heritability, levels = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))

str(make.plot)

```