---
title: "Simulation Analyses"
output: html_document
---

##Read matrix of all simulated data
```{r}
allSims <- read.table(file = "../all_sim_data/simulation_analyses_0.6/simulation_data/Simulated.Data.100.Reps.Herit.0.6.txt",header=T,stringsAsFactors=F)
```

##Read genotypes
```{r}
genos <- read.csv("../all_sim_data/simulation_analyses_0.6/IBM_sample_final1.csv",header=T,stringsAsFactors=F,na.strings=c("-","NA"))
```

##Create Matrices for data to be inserted in to
```{r}
setwd("all_sim_data/simulation_analyses_0.6")
sigs <- read.table(file = "../all_sim_data/simulation_analyses_0.6/simulation_data/Genotypic.information.for.4.Additive.QTN.txt",stringsAsFactors=F,header=T)[,1]
twosigs <- read.table(file = "../all_sim_data/simulation_analyses_0.6/simulation_data/Genotypic.information.for.4.Epistatic.QTN.txt",stringsAsFactors=F,header=T)[,1]
results <- matrix(NA,nrow=100,ncol=5)
two.full <- matrix(NA, nrow = 9, ncol = 100)
two.add <- matrix(NA, nrow = 9, ncol = 100)
rownames(tworesults) <- c("threshold",twosigs)
```
##Loop over analysis
###Composite Interval Mapping (Additive search)
```{r}
setwd("../all_sim_data/simulation_analyses_0.6")
for(i in 2:5){

  genos.tmp <- genos
  genos.tmp[,1] <- c("","",allSims[,i])
  write.csv(genos.tmp,file=paste(i-1,".genos.tmp.csv"),row.names=F,quote=F)
  
  
  sim <- read.cross(format = "csv", ".", 
                    file=paste(i-1,".genos.tmp.csv"), na.strings=c("-","NA"), genotypes = c("A","B"))
  sim2 <- jittermap(sim, 1e-6)
  
  sim3 <- convert2riself(sim2)
  
  sim4 <- calc.genoprob(sim3)
  
  CIM <- cim(sim4, n.marcov = 6, window = 10, method = "hk")
  
  CIMperms <- cim(sim4, n.marcov = 6, window= 10, method = "hk", n.perm = 100)
  
  thresh <- summary(CIMperms)[1,1]
  
  lod <- as.matrix(CIM$lod)
  rownames(lod) <- colnames(genos)[2:1340]
  first<- c(thresh,lod[rownames = sigs,])
  results[i-1,1:5] <- first
}
```

###Scantwo (epistatic search)
```{r}
f <- function(foo) {
    foo[upper.tri(foo)] <- t(foo)[upper.tri(foo)]
    foo}
g <- function(foo){
  foo[lower.tri(foo)] <- t(foo)[lower.tri(foo)]
    foo}
setwd("all_sim_data/simulation_analyses_0.6")
for(i in 1:100){
  
  sim <- read.cross(format = "csv", ".", file=paste(i,".genos.tmp.csv"),
                    na.strings=c("-","NA"), genotypes = c("A","B"))
  sim <- jittermap(sim, 1e-6)
  sim <- convert2riself(sim)
  sim <- calc.genoprob(sim)
  
  scantwo <- scantwo(sim, chr = c(1,2,3,4,5,6,7,8,9,10), pheno.col = 1, model = "normal", method = "hk", addcovar = NULL, intcovar = NULL, weights = NULL, use = "all.obs")
  
  scantwoperms <- scantwo(sim, chr = c(1,2,3,4,5,6,7,8,9,10), pheno.col = 1, model = "normal", method = "hk", addcovar = NULL, intcovar = NULL, weights = NULL, use = "all.obs", n.perm = 1)
  
  scantwosum <- summary(scantwo, perm = scantwoperms, alpha = 0.05)
  twothresh <- summary(scantwoperms)[[1]][1]
  
  foo <- matrix(scantwo$lod, nrow = 1339, ncol = 1339)
  foo.full <- f(foo)
  foo.add <- g(foo)
  rownames(foo.full) <- rownames(CIM)
  colnames(foo.full) <- rownames(CIM)
  rownames(foo.add) <- rownames(CIM)
  colnames(foo.add) <- rownames(CIM)
  full1x2 <- foo.full[rownames = twosigs[1],colnames = twosigs[2]]
  
  full3x4 <- foo.full[rownames = twosigs[3],colnames = twosigs[4]]
  
  full5x6 <- foo.full[rownames = twosigs[5],colnames = twosigs[6]]
  
  full7x8 <- foo.full[rownames = twosigs[7],colnames = twosigs[8]]
  
  add1x2 <- foo.add[rownames = twosigs[1],colnames = twosigs[2]]
  
  add3x4 <- foo.add[rownames = twosigs[3],colnames = twosigs[4]]
  
  add5x6 <- foo.add[rownames = twosigs[5],colnames = twosigs[6]]
  
  add7x8 <- foo.add[rownames = twosigs[7],colnames = twosigs[8]]
  
  full.cols <- rbind(twothresh,full1x2,"",full3x4,"",full5x6,"",full7x8,"") 
  add.cols <- rbind(twothresh,add1x2,"",add3x4,"",add5x6,"",add7x8,"")
  two.full[,i] <- full.cols
  two.add[,i] <- add.cols
  }
```

##Export results to csv files
```{r}
  setwd("all_sim_data/simulation_analyses_0.6")
write.csv(two.full, file = paste("results.epistatic.full.0.6.csv"))
write.csv(two.add, file = paste("results.epistatic.add.0.6.csv"))

write.csv(results, file = paste("results.additive.0.6.csv"))
```
